version: '3'
networks:
  my-app-network: null

services:
  proxy:
    image: nginx:alpine
    container_name: web-proxy
    restart: unless-stopped
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${GATEWAY_PORT}:80
    depends_on:
      - back-end
      - my-database-for-node-app
      - front-end
    environment:
      - BE_PORT=${BE_PORT}
    networks:
      - my-app-network

  back-end:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: back-end
    ports:
      - '${BE_PORT}:${BE_PORT}'
    volumes:
      - .:/app
      - '/app/node_modules'
    networks:
      - my-app-network
    depends_on:
      - my-database-for-node-app
    environment:
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USER=${DB_USER}

      - BE_PORT=${BE_PORT}
      - DB_PORT=${DB_PORT}
  ###################################################################
  my-database-for-node-app:
    image: mysql:8.0
    container_name: '${DB_HOST}'
    networks:
      - my-app-network
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '${DB_PORT}:3306'

  front-end:
    image: linhleba/admin-panel
    container_name: front-end
    ports:
      - '3000:3000'
    networks:
      - my-app-network
    depends_on:
      - my-database-for-node-app
      - back-end
