name: Docker Image CI

on:
  push:
    branches: [ ci/cd ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag duytronguit/ecommerce
    - name: Get Docker Hub Credentials
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push image
      run: docker push duytronguit/ecommerce
    - uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DO_PAT }}
    - run: doctl compute ssh root@kltn / docker-compose down / docker-compose build / docker-compose up