on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Deploy via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DO_HOST }}
        username: ${{ secrets.DO_USER }}
        key:  ${{ secrets.PRIVATE_KEY_ACCESS_DO }}
        script: |
          cd BE_E-ComerceSite/
          git pull origin master
          docker image build . -f Dockerfile --tag back-end
          docker rm -f back-end
          docker run --name back-end --network=be_e-comercesite_my-app-network back-end