name: Docker Image CI

on:
  push:
    branches: [ ci/cd ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag duytronguit/ecommerce

    - name: Get DockerHub Credentials
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push image
      run: docker push duytronguit/ecommerce

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DO_PAT }}

    - name: Create SSH key
      run: |
        mkdir -p ~/.ssh/
        cd ~/.ssh
        echo "$SSH_PRIVATE_KEY" > id_rsa
        echo "$SSH_PUBLIC_KEY" > id_rsa.pub
        echo "$SSH_KNOWN_HOSTS" > known_hosts
        chmod 400 ~/.ssh/id_rsa
      shell: bash
      env:
        SSH_PRIVATE_KEY:  ${{ secrets.PRIVATE_KEY_ACCESS_DO }}
        SSH_PUBLIC_KEY:  ${{ secrets.PUBLIC_KEY }}
        SSH_KNOWN_HOSTS:  ${{ secrets.KNOWN_HOSTS }}

    - name: Get source code
      run: |
        doctl compute ssh kltn
        docker-compose down
        docker-compose build
        docker-compose up
      shell: bash
      env:
        DB_NAME = {{ secrets.DB_NAME }}
        DB_HOST={{ secrets.DB_HOST }}
        DB_PORT={{ secrets.DB_PORT }}
        DB_PASSWORD={{ secrets.DB_PASSWORD }}
        DB_USER={{ secrets.DB_USER }}
        DB_ROOT_PASSWORD={{ secrets.DB_ROOT_PASSWORD }}

        BE_PORT={{ secrets.BE_PORT }}
        ACCESS_JWT_SECRET={{ secrets.ACCESS_JWT_SECRET }}
        REFRESH_JWT_SECRET={{ secrets.REFRESH_JWT_SECRET }}